[package]
name = "ao-engine-tools-core"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
ao-persistence = { workspace = true }
ao-protocol = { workspace = true }
ao-search-index = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true }
