//! Slack app manifest generation — the prefilled YAML a user pastes into
//! Slack's "Create app → From an app manifest" flow so they never hand-check
//! a scope list.
//!
//! [`SLACK_REQUIRED_BOT_SCOPES`], [`SLACK_REQUIRED_APP_TOKEN_SCOPE`], and
//! [`SLACK_REQUIRED_EVENT_SUBSCRIPTIONS`] are the single source of truth for
//! what a working Slack connection needs: [`generate_slack_app_manifest`]
//! reads them to build the manifest, and Test Connection's scope diff
//! (`ao_engine::channels::slack::test_connection`) reads the same constants
//! to grade a token's granted scopes against them. Two independently
//! maintained copies of this list — one baked into the manifest, one used to
//! validate against — is exactly the drift this module exists to prevent.

use serde::Serialize;

/// Bot token (`xoxb-…`) scopes every Slack binding needs. Order here is the
/// order they appear in the generated manifest and in a Test Connection
/// scope diff.
pub const SLACK_REQUIRED_BOT_SCOPES: &[&str] = &[
    "app_mentions:read",
    "chat:write",
    "im:history",
    "im:read",
    "im:write",
    "channels:history",
    "groups:history",
    "users:read",
];

/// App-level token (`xapp-…`) scope Socket Mode needs. Slack's app manifest
/// schema has no field for app-level token scopes — those are only
/// generated by hand, from the app's "Basic Information" page, after the
/// app itself exists — so this constant surfaces as a comment instruction in
/// the generated manifest rather than a YAML field. It is proven at
/// Test Connection time by the `apps.connections.open` handshake check
/// succeeding: that endpoint requires this exact scope on the token used to
/// call it.
pub const SLACK_REQUIRED_APP_TOKEN_SCOPE: &str = "connections:write";

/// Event Subscriptions topics the bot must receive: an `@mention` anywhere,
/// a DM, and a message in a public or private channel the bot has been
/// invited to (channel/group history are both needed since either kind of
/// channel can host the bot).
pub const SLACK_REQUIRED_EVENT_SUBSCRIPTIONS: &[&str] =
    &["app_mention", "message.im", "message.channels", "message.groups"];

/// Slack's app manifest schema (version 1) caps `display_information.name`
/// at 35 characters.
const MANIFEST_NAME_MAX_CHARS: usize = 35;

const DEFAULT_APP_NAME: &str = "Launchpad Agent";

#[derive(Debug, Serialize)]
struct Manifest {
    display_information: DisplayInformation,
    features: Features,
    oauth_config: OauthConfig,
    settings: Settings,
}

#[derive(Debug, Serialize)]
struct DisplayInformation {
    name: String,
}

#[derive(Debug, Serialize)]
struct Features {
    bot_user: BotUser,
}

#[derive(Debug, Serialize)]
struct BotUser {
    display_name: String,
    always_online: bool,
}

#[derive(Debug, Serialize)]
struct OauthConfig {
    scopes: Scopes,
}

#[derive(Debug, Serialize)]
struct Scopes {
    bot: Vec<String>,
}

#[derive(Debug, Serialize)]
struct Settings {
    event_subscriptions: EventSubscriptions,
    interactivity: Interactivity,
    org_deploy_enabled: bool,
    socket_mode_enabled: bool,
    token_rotation_enabled: bool,
}

#[derive(Debug, Serialize)]
struct EventSubscriptions {
    bot_events: Vec<String>,
}

#[derive(Debug, Serialize)]
struct Interactivity {
    is_enabled: bool,
}

/// Clamps `name` to Slack's manifest name length limit and falls back to
/// [`DEFAULT_APP_NAME`] for an empty (or all-whitespace) agent name, so a
/// freshly created agent with no name set still gets a pasteable manifest.
fn sanitized_app_name(name: &str) -> String {
    let trimmed = name.trim();
    if trimmed.is_empty() {
        return DEFAULT_APP_NAME.to_string();
    }
    trimmed.chars().take(MANIFEST_NAME_MAX_CHARS).collect()
}

/// Builds the full pasteable manifest: a leading comment block (the
/// app-level token step Slack's schema can't express, per
/// [`SLACK_REQUIRED_APP_TOKEN_SCOPE`]'s doc) followed by the YAML manifest
/// itself, with Socket Mode enabled and every required bot scope and event
/// subscription pre-set.
pub fn generate_slack_app_manifest(app_name: &str) -> String {
    let name = sanitized_app_name(app_name);
    let manifest = Manifest {
        display_information: DisplayInformation { name: name.clone() },
        features: Features {
            // `false` ties the bot's presence dot to whether a Socket Mode
            // connection is actually open, rather than always showing
            // online — accurate today (no bridge exists yet, so the bot
            // should read offline) and still accurate once a runner exists
            // to open that connection.
            bot_user: BotUser { display_name: name, always_online: false },
        },
        oauth_config: OauthConfig {
            scopes: Scopes {
                bot: SLACK_REQUIRED_BOT_SCOPES.iter().map(|s| s.to_string()).collect(),
            },
        },
        settings: Settings {
            event_subscriptions: EventSubscriptions {
                bot_events: SLACK_REQUIRED_EVENT_SUBSCRIPTIONS.iter().map(|s| s.to_string()).collect(),
            },
            interactivity: Interactivity { is_enabled: false },
            org_deploy_enabled: false,
            socket_mode_enabled: true,
            token_rotation_enabled: false,
        },
    };

    let yaml = serde_yaml::to_string(&manifest)
        .expect("a manifest built entirely from plain strings and bools always serializes");

    format!(
        "# Paste this into Slack's \"Create New App → From an app manifest\" flow.\n\
         #\n\
         # After the app is created, Slack still requires one manual step this\n\
         # manifest cannot do for you: go to \"Basic Information → App-Level\n\
         # Tokens\", click \"Generate Token and Scopes\", and add the\n\
         # `{app_token_scope}` scope. That token (starts with `xapp-`) is what\n\
         # Socket Mode's handshake check uses.\n\
         #\n\
         # Then, from \"OAuth & Permissions\", install the app to your workspace\n\
         # and copy the Bot User OAuth Token (starts with `xoxb-`). Paste both\n\
         # tokens back into Launchpad's Slack setup screen.\n\
         {yaml}",
        app_token_scope = SLACK_REQUIRED_APP_TOKEN_SCOPE,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parsed_manifest_yaml(app_name: &str) -> serde_yaml::Value {
        let full = generate_slack_app_manifest(app_name);
        // The YAML document is everything after the leading `#` comment
        // block — find the first non-comment line and parse from there.
        let yaml_start = full
            .lines()
            .position(|line| !line.trim_start().starts_with('#') && !line.trim().is_empty())
            .expect("manifest has a non-comment body");
        let yaml_body: String = full.lines().skip(yaml_start).collect::<Vec<_>>().join("\n");
        serde_yaml::from_str(&yaml_body).expect("generated manifest body is valid YAML")
    }

    #[test]
    fn manifest_enables_socket_mode() {
        let value = parsed_manifest_yaml("My Agent");
        assert_eq!(value["settings"]["socket_mode_enabled"], serde_yaml::Value::Bool(true));
    }

    #[test]
    fn manifest_lists_every_required_bot_scope() {
        let value = parsed_manifest_yaml("My Agent");
        let scopes: Vec<String> = value["oauth_config"]["scopes"]["bot"]
            .as_sequence()
            .expect("bot scopes is a sequence")
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        assert_eq!(scopes, SLACK_REQUIRED_BOT_SCOPES.to_vec());
    }

    #[test]
    fn manifest_lists_every_required_event_subscription() {
        let value = parsed_manifest_yaml("My Agent");
        let events: Vec<String> = value["settings"]["event_subscriptions"]["bot_events"]
            .as_sequence()
            .expect("bot_events is a sequence")
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        assert_eq!(events, SLACK_REQUIRED_EVENT_SUBSCRIPTIONS.to_vec());
    }

    #[test]
    fn manifest_comment_documents_the_app_level_token_scope() {
        let full = generate_slack_app_manifest("My Agent");
        assert!(full.contains(SLACK_REQUIRED_APP_TOKEN_SCOPE));
        assert!(full.contains("xapp-"));
        assert!(full.contains("xoxb-"));
    }

    #[test]
    fn manifest_uses_the_given_app_name() {
        let value = parsed_manifest_yaml("My Agent");
        assert_eq!(value["display_information"]["name"], serde_yaml::Value::String("My Agent".to_string()));
        assert_eq!(
            value["features"]["bot_user"]["display_name"],
            serde_yaml::Value::String("My Agent".to_string())
        );
    }

    #[test]
    fn manifest_falls_back_to_a_default_name_when_blank() {
        let value = parsed_manifest_yaml("   ");
        assert_eq!(
            value["display_information"]["name"],
            serde_yaml::Value::String(DEFAULT_APP_NAME.to_string())
        );
    }

    #[test]
    fn manifest_truncates_a_name_longer_than_slacks_limit() {
        let long_name = "x".repeat(MANIFEST_NAME_MAX_CHARS + 20);
        let value = parsed_manifest_yaml(&long_name);
        let name = value["display_information"]["name"].as_str().unwrap();
        assert_eq!(name.chars().count(), MANIFEST_NAME_MAX_CHARS);
    }
}
