//! Outbound email message construction and the SMTP send seam.
//!
//! [`build_message`] is pure — it turns an [`OutboundEmail`] into a real
//! `lettre::Message` with no network involved, so tests can assert on the
//! exact headers and body a call produces without a live SMTP server.
//! [`SmtpSender`] is the seam over the actual network send: [`LettreSmtpSender`]
//! is the only implementation that opens a socket; a test double can stand in
//! for it wherever the tool's `invoke` path needs exercising without SMTP.

use async_trait::async_trait;
use lettre::message::Mailbox;
use lettre::transport::smtp::authentication::Credentials;
use lettre::transport::smtp::response::{Category, Severity};
use lettre::{AsyncSmtpTransport, AsyncTransport, Message, Tokio1Executor};

/// Everything needed to compose one outbound email. Threading fields
/// (`in_reply_to`/`references`) are pre-normalized (already `<...>`-wrapped)
/// by the caller — see `super::normalize_message_id`.
#[derive(Clone)]
pub struct OutboundEmail {
    pub from: String,
    pub to: Vec<String>,
    pub cc: Vec<String>,
    pub subject: String,
    pub body: String,
    pub in_reply_to: Option<String>,
    pub references: Option<String>,
    /// This message's own `<...>`-wrapped `Message-ID`, generated by the
    /// caller before sending so the same value can be returned to the agent
    /// on success regardless of whether the SMTP server echoes one back.
    pub message_id: String,
}

#[derive(Debug, Clone, PartialEq)]
pub struct SendOutcome {
    pub success: bool,
    pub message_id: Option<String>,
    pub error_kind: Option<SendErrorKind>,
    pub retryable: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SendErrorKind {
    TooLong,
    BadFormat,
    Forbidden,
    NotFound,
    RateLimited,
    Transient,
    Unknown,
}

#[derive(Debug)]
pub struct BuildError(pub String);

impl std::fmt::Display for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for BuildError {}

/// Builds the outbound `lettre::Message` for `email`. No network I/O —
/// entirely inspectable via `Message::formatted()`, which is exactly what
/// the unit tests below assert on.
pub fn build_message(email: &OutboundEmail) -> Result<Message, BuildError> {
    let from = parse_mailbox(&email.from)?;

    let mut builder = Message::builder()
        .from(from)
        .subject(email.subject.clone())
        .message_id(Some(email.message_id.clone()));

    for addr in &email.to {
        builder = builder.to(parse_mailbox(addr)?);
    }
    for addr in &email.cc {
        builder = builder.cc(parse_mailbox(addr)?);
    }
    if let Some(id) = &email.in_reply_to {
        builder = builder.in_reply_to(id.clone());
    }
    if let Some(refs) = &email.references {
        builder = builder.references(refs.clone());
    }

    builder
        .body(email.body.clone())
        .map_err(|e| BuildError(format!("failed to build message body: {e}")))
}

fn parse_mailbox(address: &str) -> Result<Mailbox, BuildError> {
    address
        .trim()
        .parse::<Mailbox>()
        .map_err(|e| BuildError(format!("invalid email address {address:?}: {e}")))
}

/// The actual outbound send. Implemented for real by [`LettreSmtpSender`];
/// stand in a fake in tests that need to exercise the tool's `invoke` path
/// without a live SMTP server.
#[async_trait]
pub trait SmtpSender: Send + Sync {
    async fn send(&self, host: &str, port: u16, username: &str, password: &str, email: &OutboundEmail) -> SendOutcome;
}

/// SMTP port lettre treats as implicit TLS (the connection is TLS-wrapped
/// from the first byte). Any other port uses STARTTLS instead — an
/// unencrypted handshake that upgrades to TLS before authenticating.
const IMPLICIT_TLS_PORT: u16 = 465;

pub struct LettreSmtpSender;

#[async_trait]
impl SmtpSender for LettreSmtpSender {
    async fn send(&self, host: &str, port: u16, username: &str, password: &str, email: &OutboundEmail) -> SendOutcome {
        let message = match build_message(email) {
            Ok(m) => m,
            Err(e) => {
                tracing::warn!("SendEmail: failed to build outbound message: {e}");
                return SendOutcome {
                    success: false,
                    message_id: None,
                    error_kind: Some(SendErrorKind::BadFormat),
                    retryable: false,
                };
            }
        };

        let builder = if port == IMPLICIT_TLS_PORT {
            AsyncSmtpTransport::<Tokio1Executor>::relay(host)
        } else {
            AsyncSmtpTransport::<Tokio1Executor>::starttls_relay(host)
        };
        let transport = match builder {
            Ok(b) => b
                .port(port)
                .credentials(Credentials::new(username.to_string(), password.to_string()))
                .build(),
            Err(e) => {
                tracing::warn!("SendEmail: failed to configure SMTP transport for {host}:{port}: {e}");
                return SendOutcome {
                    success: false,
                    message_id: None,
                    error_kind: Some(SendErrorKind::Transient),
                    retryable: true,
                };
            }
        };

        match transport.send(message).await {
            Ok(_) => SendOutcome {
                success: true,
                message_id: Some(email.message_id.clone()),
                error_kind: None,
                retryable: false,
            },
            Err(e) => {
                // Never surface the password (only ever passed to
                // `Credentials::new` above, never logged or included in `e`'s
                // Display output, which is lettre's own error text).
                tracing::warn!("SendEmail: SMTP send to {host}:{port} failed: {e}");
                let (error_kind, retryable) = classify_smtp_error(&e);
                SendOutcome { success: false, message_id: None, error_kind: Some(error_kind), retryable }
            }
        }
    }
}

/// Approximate classification of an SMTP send failure. Timeouts and 4yz
/// transient responses are retryable; permanent 5yz responses are split by
/// category where the response code makes the cause reasonably clear (mail
/// system rejection = recipient not found, `552` = message too large,
/// unspecified-3xx = the range `53x` auth/relay-denied codes commonly use);
/// anything else falls back to `Unknown`/not-retryable rather than guessing.
fn classify_smtp_error(e: &lettre::transport::smtp::Error) -> (SendErrorKind, bool) {
    if e.is_timeout() || e.is_transient() {
        return (SendErrorKind::Transient, true);
    }
    if let Some(code) = e.status() {
        if code.severity == Severity::PermanentNegativeCompletion {
            return match code.category {
                Category::MailSystem if (code.detail as u8) == 2 => (SendErrorKind::TooLong, false),
                Category::MailSystem => (SendErrorKind::NotFound, false),
                Category::Unspecified3 => (SendErrorKind::Forbidden, false),
                _ => (SendErrorKind::Unknown, false),
            };
        }
    }
    if e.is_client() {
        return (SendErrorKind::BadFormat, false);
    }
    (SendErrorKind::Unknown, true)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base_email() -> OutboundEmail {
        OutboundEmail {
            from: "agent@example.org".to_string(),
            to: vec!["user@example.com".to_string()],
            cc: vec![],
            subject: "Hello there".to_string(),
            body: "This is the body.".to_string(),
            in_reply_to: None,
            references: None,
            message_id: "<generated-1@example.org>".to_string(),
        }
    }

    fn formatted(msg: &Message) -> String {
        String::from_utf8(msg.formatted()).expect("formatted message is valid utf8")
    }

    #[test]
    fn builds_to_cc_subject_and_message_id() {
        let mut email = base_email();
        email.cc = vec!["watcher@example.org".to_string()];
        let msg = build_message(&email).expect("builds");
        let text = formatted(&msg);

        assert!(text.contains("To: user@example.com"));
        assert!(text.contains("Cc: watcher@example.org"));
        assert!(text.contains("Subject: Hello there"));
        assert!(text.contains("Message-ID: <generated-1@example.org>"));
        assert!(text.contains("This is the body."));
    }

    #[test]
    fn omits_cc_header_when_no_cc_addresses() {
        let msg = build_message(&base_email()).expect("builds");
        assert!(!formatted(&msg).contains("Cc:"));
    }

    #[test]
    fn threads_in_reply_to_and_references_when_present() {
        let mut email = base_email();
        email.in_reply_to = Some("<original@example.com>".to_string());
        email.references = Some("<original@example.com>".to_string());
        let msg = build_message(&email).expect("builds");
        let text = formatted(&msg);

        assert!(text.contains("In-Reply-To: <original@example.com>"));
        assert!(text.contains("References: <original@example.com>"));
    }

    #[test]
    fn omits_threading_headers_for_a_new_email() {
        let msg = build_message(&base_email()).expect("builds");
        let text = formatted(&msg);
        assert!(!text.contains("In-Reply-To:"));
        assert!(!text.contains("References:"));
    }

    #[test]
    fn supports_multiple_recipients() {
        let mut email = base_email();
        email.to = vec!["a@example.com".to_string(), "b@example.com".to_string()];
        let msg = build_message(&email).expect("builds");
        let text = formatted(&msg);
        assert!(text.contains("a@example.com"));
        assert!(text.contains("b@example.com"));
    }

    #[test]
    fn rejects_an_invalid_recipient_address() {
        let mut email = base_email();
        email.to = vec!["not-an-address".to_string()];
        let err = build_message(&email).expect_err("must reject malformed address");
        assert!(err.0.contains("not-an-address"));
    }
}
